# Generated by Django 5.2.17 on 2026-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userorganizationrole_single_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file_path',
            field=models.FileField(upload_to='media/evidences/%Y/%m/'),
        ),
    ]
