# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_evidence_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('MFA_CODE', 'Code MFA'), ('WELCOME', 'Bienvenue'), ('RECOVERY', 'Récupération'), ('INVITATION', 'Invitation Organisation'), ('OVERDUE_TASK_ALERT', 'Alerte Tâche en Retard'), ('RISK_NOTIFICATION', 'Notification de Risque')], max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='api.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'email_type'], name='api_emaillo_user_id_f86e2f_idx'), models.Index(fields=['organization'], name='api_emaillo_organiz_947f32_idx')],
            },
        ),
    ]
