# Generated by Django 5.2.17 on 2026-10-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_isocontrol_embedding_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='isocontrol',
            name='keywords',
            field=models.TextField(blank=True, help_text='Mots-clés ou synonymes associés au contrôle pour enrichir la recherche vectorielle.', null=True),
        ),
    ]
