services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: open_smr_postgres
    restart: always
    environment:
      POSTGRES_DB: open_smr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: